version: '3'
services:
  web:
    build: .
    command: bash -c "bundle exec rails s -b '0.0.0.0' -p 3001"
    volumes:
      - ".:/app"
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      RABBITMQ_URL: http://rabbitmq:5672
      MONGO_URL: mongo:27017

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"